import MainLayout from '@/Layout';
import OrderHistoryView from '@/Views/OrderHistory';
import Head from 'next/head';
import React from 'react';
import cookie from 'cookie';
import jwt from 'jsonwebtoken';
import userAut from '@/Helper/Authorization/userAut';

export default function OrderHistory() {
  return (
    <>
      <Head>
        <title>Foodie Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <OrderHistoryView />
      </MainLayout>
    </>
  );
}

export async function getServerSideProps(context) {
  let cookieHeader = context.req.headers.cookie;

  if (typeof cookieHeader !== 'string') {
    cookieHeader = '';
  }
  const cookies = cookie.parse(cookieHeader).token;
  const jwtData = jwt.decode(cookies);
  const authResult = userAut(jwtData, cookies);
  if (authResult) return authResult;
  return {
    props: {},
  };
}
