import Head from 'next/head';
import cookie from 'cookie';
import MainLayout from '@/Layout';
import FavoriteMenu from '@/Views/FavoriteMenu';
import jwt from 'jsonwebtoken';
import userAut from '@/Helper/Authorization/userAut';

export default function Favorite() {
  return (
    <>
      <Head>
        <title>Foodie Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <FavoriteMenu />
      </MainLayout>
    </>
  );
}

export async function getServerSideProps(context) {
  const cookieHeader = context.req.headers.cookie || '';

  const cookies = cookie.parse(cookieHeader)?.token || '';
  const jwtData = jwt.decode(cookies);
  const authResult = userAut(jwtData, cookies);
  if (authResult) return authResult;
  return {
    props: {
      // ...
    },
  };
}
