import Head from "next/head";
import { Inter } from "next/font/google";
import cookie from "cookie";
import MainLayout from "@/Layout";
import FavoriteMenu from "@/Views/FavoriteMenu";
import jwt from "jsonwebtoken";

export default function Favorite() {
  return (
    <>
      <Head>
        <title>Foodie Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <FavoriteMenu />
      </MainLayout>
    </>
  );
}

export async function getServerSideProps(context) {
  const cookieHeader = context.req.headers.cookie;

  const cookies = cookie.parse(cookieHeader).token;
  if (!cookies) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const jwtData = jwt.decode(cookies);
  if (jwtData.role === "admin") {
    return {
      redirect: {
        destination: "/admin",
        permanent: false,
      },
    };
  }
  return {
    props: {
      // ...
    },
  };
}
