import Head from "next/head";
import { Inter } from "next/font/google";
import cookie from "cookie";
import MainLayout from "@/Layout";
import HomeMenu from "@/Views/HomeMenu";
import jwt from "jsonwebtoken";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>foodie order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <HomeMenu />
      </MainLayout>
    </>
  );
}

export async function getServerSideProps(context) {
  let cookieHeader = context.req.headers.cookie;

  if (typeof cookieHeader !== "string") {
    cookieHeader = "";
  }
  const cookies = cookie.parse(cookieHeader).token;
  if (!cookies) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const jwtData = jwt.decode(cookies);
  if (jwtData.role === "admin") {
    return {
      redirect: {
        destination: "/admin",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
}
