import MainLayout from "@/Layout";
import HomeMenu from "@/Views/HomeMenu";
import { parse } from "cookie";
import Head from "next/head";
import React from "react";
import jwt from "jsonwebtoken";

export default function ProductFilterByKategori() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <HomeMenu />
      </MainLayout>
    </>
  );
}

export async function getServerSideProps(context) {
  let cookieHeader = context.req.headers.cookie;

  console.log("ini : ", cookieHeader);
  if (typeof cookieHeader !== "string") {
    cookieHeader = "";
  }
  const cookies = parse(cookieHeader).token;
  if (!cookies) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  const jwtData = jwt.decode(cookies);
  if (jwtData.role === "admin") {
    return {
      redirect: {
        destination: "/admin",
        permanent: false,
      },
    };
  }
  return {
    props: {
      // ...
    },
  };
}
