import MainLayout from '@/Layout';
import HomeMenu from '@/Views/HomeMenu';
import { parse } from 'cookie';
import Head from 'next/head';
import React from 'react';
import jwt from 'jsonwebtoken';
import userAut from '@/Helper/Authorization/userAut';

export default function ProductFilterByKategori() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <HomeMenu />
      </MainLayout>
    </>
  );
}

export async function getServerSideProps(context) {
  let cookieHeader = context.req.headers.cookie;
  if (typeof cookieHeader !== 'string') {
    cookieHeader = '';
  }
  const cookies = parse(cookieHeader).token;
  const jwtData = jwt.decode(cookies);
  const authResult = userAut(jwtData, cookies);
  if (authResult) return authResult;
  return {
    props: {
      // ...
    },
  };
}
