import MainLayout from "@/Layout";
import HomeMenu from "@/Views/HomeMenu";
import { parse } from "cookie";
import Head from "next/head";
import React from "react";

export default function ProductFilterByKategori() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <MainLayout>
        <HomeMenu />
      </MainLayout>
    </>
  );
}

// export async function getServerSideProps(context) {
//   const category = context.query.kategori;

//   const cookieString = context.req.headers.cookie;
//   const cookies = parse(cookieString);
//   const token = cookies.token;

// const response = await fetch("http://localhost:5000/kategori", {
//   method: "POST",
//   headers: {
//     // "Content-Type": "application/json",
//     Authorization: `Bearer ${token}`,
//   },
//   body: JSON.stringify({
//         kategori: category,
//         page,
//         limit,
//         // search: searchValue,
//   }),
// });

// return {
//   props: {},
// };
// }
export async function getServerSideProps(context) {
  const cookieHeader = context.req.headers.cookie;

  if (!cookieHeader) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  // Mendapatkan header cookies dari permintaan
  const cookies = parse(cookieHeader).token;
  // Lakukan sesuatu dengan cookies
  console.log(cookies);
  if (!cookies) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    props: {
      // ...
    },
  };
}
